In [3]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

import pandas as pd
iris = pd.read_csv('iris_1D.csv')

X_train = iris.iloc[:,:-1].values
y_train = iris.iloc[:,1].values


In [4]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
classifier = GaussianNB()

clf = classifier.fit(X_train, y_train)


In [5]:
X_test  = np.array([[3.0]])
clf.predict_proba(X_test)

array([[0.0454125, 0.9545875]])

In [6]:
clf.class_count_

array([5., 5.])

## COMPUTE MANUALLY

In [7]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [8]:
data_c0 = np.array([1.4, 1.0, 1.3, 1.9, 2.0])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()
prob_c0 = gaussian_function(data_c0, mean_c0, var_c0)
prob_c0

array([1.00761742, 0.40804972, 0.893626  , 0.63670363, 0.46995266])

In [9]:
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)

In [10]:

dpf_c0_x = gaussian_function(X_test, mean_c0, var_c0)
dpf_c1_x = gaussian_function(X_test, mean_c1, var_c1)

prob_1 = (0.5*dpf_c0_x)/(0.5*dpf_c0_x+0.5*dpf_c1_x)
print(prob_1, 1-prob_1)

[[0.0454125]] [[0.9545875]]


In [11]:
iris_1 = pd.read_csv('iris_2D.csv')

X_train1 = iris_1.iloc[:, :-1].values
y_train1 = iris_1.iloc[:, -1].values

classifier_1 = GaussianNB()
clf = classifier_1.fit(X_train1, y_train1)

X_test_1 = np.array([[4.1, 2.9]])
print(clf.predict_proba(X_test_1))
clf.predict(X_test_1)


 

[[0.996191 0.003809]]


array([0], dtype=int64)

In [12]:
iris_2 = pd.read_csv('iris_2D_3C.csv')

X_train1 = iris_2.iloc[:, :-1].values
y_train1 = iris_2.iloc[:, -1].values

classifier_2 = GaussianNB()
clf = classifier_2.fit(X_train1, y_train1)

X_test_2 = np.array([[5.2, 2.4]])
print(clf.predict_proba(X_test_2))
clf.predict(X_test_2)

[[0.0418694  0.19180669 0.76632391]]


array([2], dtype=int64)